@startuml
left to right direction
actor User
usecase CartManager as CartManager
usecase AddToCart as AddToCart
usecase UpdateCart as UpdateCart
usecase DeleteCart as DeleteCart

User -> CartManager
CartManager <|-- AddToCart : <<extend>>
CartManager <|-- UpdateCart : <<extend>>
CartManager <|-- DeleteCart : <<extend>>
@enduml
